import type { CSSProperties } from "hono/jsx";
import { monospaceFont } from "../../styles";

export const styles: Record<string, CSSProperties> = {
  root: {
    boxSizing: "border-box",
    color: "#f1f5f9",
    display: "flex",
    flexDirection: "column",
    fontSize: 14,
    gap: 16,
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  title: {
    color: "#fff",
    fontSize: 24,
    fontWeight: 600,
    margin: 0,
  },
  description: {
    color: "#94a3b8",
    margin: 0,
  },
  panel: {
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: 8,
    color: "#f1f5f9",
  },
  panelEmpty: {
    color: "#94a3b8",
    padding: 20,
  },
  section: {
    background: "rgb(2 6 23 / 70%)",
    border: "1px solid #334155",
    borderRadius: 8,
    padding: "12px 16px",
  },
  methodPanel: {
    background: "rgb(15 23 42 / 80%)",
    border: "1px solid #334155",
    borderRadius: 8,
  },
  sectionSummary: {
    color: "#e2e8f0",
    cursor: "pointer",
    fontWeight: 500,
  },
  pre: {
    background: "#020617",
    borderRadius: 6,
    color: "#cbd5e1",
    fontSize: 12,
    overflowX: "auto",
    padding: 12,
  },
  servicePre: {
    marginTop: 12,
  },
  inlineHeader: {
    alignItems: "center",
    display: "flex",
    gap: 16,
    justifyContent: "space-between",
    marginBottom: 12,
  },
  subtitle: {
    color: "#e2e8f0",
    fontWeight: 500,
    margin: 0,
  },
  runButton: {
    background: "#0ea5e9",
    border: 0,
    borderRadius: 6,
    color: "#020617",
    cursor: "pointer",
    fontWeight: 500,
    padding: "8px 12px",
  },
  runButtonDisabled: {
    background: "#334155",
    color: "#94a3b8",
    cursor: "not-allowed",
  },
  fieldLabel: {
    color: "#94a3b8",
    display: "block",
    fontSize: 12,
    letterSpacing: "0.08em",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  formCaption: {
    color: "#94a3b8",
    fontSize: 12,
    marginBottom: 8,
  },
  textarea: {
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: 6,
    color: "#f1f5f9",
    font: "inherit",
    fontFamily: monospaceFont,
    fontSize: 12,
    marginBottom: 12,
    minHeight: 112,
    outline: 0,
    padding: 10,
    resize: "vertical",
    width: "100%",
  },
  responseHeader: {
    alignItems: "center",
    display: "flex",
    gap: 16,
    justifyContent: "space-between",
    marginBottom: 8,
  },
  responseStatus: {
    color: "#94a3b8",
    fontSize: 12,
  },
  responsePre: {
    border: "1px solid #334155",
    minHeight: 112,
  },
  runsStack: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    marginTop: 12,
  },
  runEmpty: {
    border: "1px dashed #334155",
    borderRadius: 6,
    color: "#94a3b8",
    padding: "16px 12px",
  },
  runPanel: {
    background: "rgb(2 6 23 / 80%)",
    border: "1px solid #334155",
    borderRadius: 8,
  },
  runSummary: {
    color: "#e2e8f0",
    cursor: "pointer",
    fontSize: 14,
    padding: "8px 12px",
  },
  runBody: {
    borderTop: "1px solid #334155",
    display: "flex",
    flexDirection: "column",
    gap: 24,
    padding: 12,
  },
  errorLabel: {
    color: "#fda4af",
  },
  errorPre: {
    background: "rgb(76 5 25 / 40%)",
    color: "#fecdd3",
  },
};
